### ISSUE TITLE
Suggestions to remove UIKit from library

### ISSUE THREAD

**Issue by DKvarn** [ehn-digital-green-development/ValidationCore#10]
I would suggest to remove the function with UIView `public mutating func validateQrCode(_ qrView : UIView,` and keep the library without any UIKit things to keep it as a core validation library.

Move the QR scanning functionality to the app and call `validate` from the app and handle the result in the app to keep this library clean and without dependency to UIKit.

**Comment by asitdm** [comment]
That is a reasonable suggestion, UIKit should not be required for the core functionality. I removed the dependency using a preprocessor directive, so that `validateQrCode` can still be used where UIKit is available.
