### ISSUE TITLE
Schema changes: string for sc and dr

### ISSUE THREAD

**Issue by DKvarn** [ehn-digital-green-development/ValidationCore#12]
Schema for Test are using string (with format date-time) for sc and dr.

To test use number 3 NAA and 4 RA at https://github.com/eu-digital-green-certificates/dgc-testdata/tree/main/AT, they will work after implementing the fix.

To represent the schema better PastInfections are renamed to Recovery.

See PR #9

**Comment by asitdm** [comment]
Thank you for the PR, the changes were already in the working branch, which is now merged to main.
