### ISSUE TITLE
Isn't working with TrustListV2 anymore 

### ISSUE THREAD

**Issue by mariohahn** [ehn-digital-green-development/ValidationCore#16]
It was working with https://dgc.a-sit.at/ehn/cert/list but is not working with https://dgc.a-sit.at/ehn/cert/listv2 anymore. 

Are you even planing to support v2?

**Comment by asitdm** [comment]
Hi,

thanks for bringing this up. This is currently work in progress.

**Comment by mariohahn** [comment]
is there an eta for that?

**Comment by asitdm** [comment]
Support for the new trustlist version was merged into the main branch.

**Comment by mariohahn** [comment]
Thx (:
