### ISSUE TITLE
Crashing in SwiftCBOR - tagged cbor

### ISSUE THREAD

**Issue by ArturPenta** [ehn-digital-green-development/ValidationCore#17]
`https://github.com/eu-digital-green-certificates/dgc-testdata/tree/main/BE`
If you scan 3 example from that page, app is crashing because it has tagged cbor, and SwiftCBOR is calling fattalError method, they really should use do catch mechanism and throw some error

**Comment by asitdm** [comment]
Hi,

this is an issue from the library SwiftCBOR and already mentioned [here](https://github.com/unrelentingtech/SwiftCBOR/issues/63). As soon as there is a fix available, we will include it.

**Comment by DKvarn** [comment]
@asitdm the SwiftCBOR repo isn't that active so I wouldn't bet on it to be fixed within three weeks, should be fork the repo to here and fix it or are BE using the tag wrong (I haven't looked into it so I don't know)?

**Comment by SchulzeStTSI** [comment]
@ArturPenta @DKvarn @asitdm 

We are facing the issue with the tag (0) in date times for tests. we created a fix for that: 

https://github.com/eu-digital-green-certificates/SwiftCBOR

Do you facing more tagging problems?

**Comment by asitdm** [comment]
@SchulzeStTSI Thank you, this fork resolves the tagging issue for the current set of test certificates.

**Comment by DKvarn** [comment]
I have also verified against BE and SE and it works good, thank you!

**Comment by ArturPenta** [comment]
Same for me, good work, Thank you.
