### ISSUE TITLE
Supporting V1 version of X509 certificates.

### ISSUE THREAD

**Issue by ArturPenta** [ehn-digital-green-development/ValidationCore#18]
Supporting V1 version of `X509 certificates`.
Cyprus generated `V1` version of `X509 certificates`, and `ValidationCore` is using `ASN1Decoder` dependency and that dependency has some problems to decode that certificate, every property is nil, and because of that `isValid` function will always return false, `isType` will always return false etc.

Cyprus TestData:
`https://github.com/eu-digital-green-certificates/dgc-testdata/tree/main/CY`

Related:
`https://github.com/eu-digital-green-certificates/dgc-testdata/issues/231`
`https://github.com/eu-digital-green-certificates/dgc-overview/blob/main/guides/certificate-governance.md#13terminology`

**Comment by DKvarn** [comment]
Cyprus will generate X509v3 and it should be X509v3 so there are no point of supporting X509v1, I suggest to just close this issue.

**Comment by psavva** [comment]
Please close this issue and reference https://github.com/eu-digital-green-certificates/dgc-testdata/issues/231
