### ISSUE TITLE
Unable to read QR

### ISSUE THREAD

**Issue by HannesVDB** [ehn-digital-green-development/ValidationCore#3]
Hi all,

We're trying to decrypt a QR-code we received from our instances.
But when I try to decode it. The COSE signature seems to be different.

Shouldn't all COSE signatures be the same across countries?

A colleague of mine used the Android implementation and he's able to decode a QR code which was generated on https://dgc.a-sit.at/ehn/ and is also able to scan a QR-code our instance created.. 

Could you somehow help me with the different implementations.. Because I don't fully understand why Android does work and the iOS code is so much different..

**Comment by DKvarn** [comment]
Hi,
Can it be related to https://github.com/ehn-digital-green-development/ValidationCore/issues/5 ?

**Comment by HannesVDB** [comment]
Indeed it seems that our cose is nog tagged.
And I updated the implementation like this
```
init?(from data: Data) {
        guard let decodedData = try? CBOR.decode(data.bytes) else {
            return nil
        }
        
        if let cose = try? CBORDecoder(input: data.bytes).decodeItem()?.asCose(),
           let type = CoseType.from(tag: cose.0),
           let protectedHeader = CoseHeader(from: cose.1[0]),
           let signature = cose.1[3].asBytes() {
            self.type = type
            self.protectedHeader = protectedHeader
            self.unprotectedHeader = CoseHeader(from: cose.1[1])
            self.payload = cose.1[2]
            self.signature = Data(signature)
        } else {
            guard let decodedDataList = decodedData.asList() else {
                return nil
            }
                    
            let headerCBOR = decodedDataList[0]
            guard let header = CoseHeader(from: headerCBOR) else { return nil }
            self.protectedHeader = header
                    
            let text = decodedDataList[2]
            self.payload = text

            self.unprotectedHeader = nil
            self.signature = decodedDataList[3].asData()
            self.type = .sign1
        }
    }
```

**Comment by DKvarn** [comment]
Thank you for sharing your code, I needed to make a change for it to work with https://dev.a-sit.at/certservice.
From
`CoseHeader(from: ...` 
to
`CoseHeader(fromBytestring: ...`

Did you try with https://dev.a-sit.at/certservice using your code?

**Comment by HannesVDB** [comment]
@DKvarn I din't test my code using a COSE (Base45) from the certservice since I received another signature from our instances..

**Comment by asitdm** [comment]
Hi,

thank you for the feedback. Unfortunately, different COSE libraries will output quite different structures. As there is currently no clarification how to handle untagged structures, I changed the initializer based on your code to process them as well. It works with codes generated by [https://dgc.a-sit.at/ehn](https://dgc.a-sit.at/ehn) (the successor of dev.a-sit/certservice). @HannesVDB Could you please check the changes against your implementation and close this issue, if it is resolved?

**Comment by DKvarn** [comment]
@asitdm I have looked at your change and with my examples we have List but I need to use `CoseHeader(fromBytestring: ...` now it use `CoseHeader(from: ...` for List so that's a problem for me. Should be support that the header can be in both formats? Then it should support that for both tagged and not tagged, or?

**Comment by asitdm** [comment]
@DKvarn Could you by chance give ma a link to your generation service or provide one of your QR codes for testing?

**Comment by HannesVDB** [comment]
@asitdm or @DKvarn the qr-code we have from our authorities is:
```
HC1:NCF3TDJ%B6FL9SS8UVTKULG8W9WFI1Y%7NDC3LE $CZK9TNVTWG4G5WJAN9HNO4*J8OX4W$C2VLWLIML5PYH1LALX95Y58XEDXH8NI7 93W1*%EVC2QX5$W5R$9:V5VQIZ0Q:O1NTICZU5/GX/KR96/-KKTCY73JC3DG3IFTG233ZC%CTVMFD-48YI 35Z/KCZKK3JC-4D-4HRVUMNMD3*20EJK-+K.IA9D88QEI1KY/F0JAXD15IAXMFU*GSHGRKMXGG6DBYCB-1JMJKR.KI91L4DWZJ$7K+ CMED:NKDAD1QD.ZJI7JSTNB95.16EAOEYK8L6R95D261L5N/5.KMVE4+Y5GT4D:7VT4IVQSA7G6MY1SADSKVQQQ6JINQ+MN/Q19QE8QNQOTZ8$3H9*R0MPI:140IEFFQ.7Z93S MU3T82SNFTI1F6S3HO509W4:E5P7GLT*PC2HR+FL:FOBVVCGA:SB*TSKAM+4UL5MBMDCTPB854G0TTE
```

Which is signed with:
```
-----BEGIN CERTIFICATE-----
MIICLTCCAZYCAQEwDQYJKoZIhvcNAQELBQAwfTELMAkGA1UEBhMCQkUxEzARBgNV
BAgMClNvbWUtU3RhdGUxCzAJBgNVBAoMAlZPMQ4wDAYDVQQLDAVNQUdEQTEPMA0G
A1UEAwwGQ0EtREVWMSswKQYJKoZIhvcNAQkBFhxvcnR3aW4uam9uaWF1eEB2bGFh
bmRlcmVuLmJlMB4XDTIxMDUwNTEwMjEzOVoXDTIyMDUwNTEwMjEzOVowgYcxCzAJ
BgNVBAYTAkJFMRMwEQYDVQQIDApTb21lLVN0YXRlMQswCQYDVQQKDAJWTzEOMAwG
A1UECwwFTUFHREExGTAXBgNVBAMMEERFVi1BdHRlc3RhdGlvbnMxKzApBgkqhkiG
9w0BCQEWHG9ydHdpbi5qb25pYXV4QHZsYWFuZGVyZW4uYmUwWTATBgcqhkjOPQIB
BggqhkjOPQMBBwNCAATeOZDvexQEQOmQohMeBCkyrIw7w9B16TcXFRfAOmmmg2nv
xkChDQHlkwaGG8NhFkeUET3sAShyVM1duny+16yuMA0GCSqGSIb3DQEBCwUAA4GB
AKue+KOyCv4/GAF28PC5ZWL9n9nt86x4LoftWji76uTTC+1QVWLhyFhfvXMfhArn
u9OY/Te1jIyxWROuJv5QVa8h5BMpvV2DdFd7YmpoRN+UuAs6Dd+ve+m82up0Yww/
r4cnUsPorHGNPbBILJOXxhxi9mu1Jrd4pgWr+oXTipft
-----END CERTIFICATE-----
```

It seems that it's not possible to decode de CBOR.. So I updated the `init` from the `Cose.swift` to the following

```
init?(from data: Data) {
        guard let decodedData = try? CBOR.decode(data.bytes) else {
            return nil
        }

        guard let decodedDataList = decodedData.asList() else {
            return nil
        }
                
        let headerCBOR = decodedDataList[0]
        guard let header = CoseHeader(from: headerCBOR) else { return nil }
        self.protectedHeader = header
                
        let text = decodedDataList[2]
        self.payload = text

        self.unprotectedHeader = nil
        self.signature = decodedDataList[3].asData()
        self.type = .sign1
    }
```

Where the `CoseHeader` has the following `init`

```
init?(from cbor: CBOR) {
            guard let cborMap = cbor.decodeBytestring()?.asMap() else { return nil }
            guard let alg = cborMap[1],
                  let value = alg.asUInt64(),
                  let algortithm = Algorithm(rawValue: value) else {
                return nil
            }
            self.algorithm = algortithm
            self.keyId = cborMap[4]?.asBytes()
            self.rawHeader = cbor
        }
```

This works for the decode of the CBOR.. But the TrustlistService can't decode my .der or .cert I created.. 

Any ideas how we could update this?

**Comment by dirkx** [comment]
Your data decodes as:

     pbpaste | sed -e 's/^HC1://'   | base45 --decode | zlib-flate -uncompress | cose_dumper 
     [
       h'a201260448cbe813fb712a0fab', 
       {}, 
            h'a401624245041a60b9ff14061a60927214390103a101a4617681aa626369782432326437356138322d623364632d343330332d626131382d38653537383963613736313562636f62424562646e016264746a323032312d30342d30326269736f654865616c74682042656c6769756d626d616d4f52472d313030303031363939626d706643566e436f5662736402627467693834303533393030366276706a3131313933343930303763646f626a313938342d31322d3133636e616da462666e664f727477696e62676e674a6f6e6961757863666e74664f525457494e63676e74674a4f4e494155586376657265312e302e30', 
  h'04160c04574da4fcf0dac56a4839e6b95cc57d99a82d8d5bf83e370885a8adfd3b43ed9242d9015756a45a5b51e52f7d5a3f0ab05e4bd4db8a7379f537aa3ce5'
     ]

So expected was a tag (18) followed by an array of 4 entries. It is untagged.

The protected header then breaks into

      echo a201260448cbe813fb712a0fab | xxd -r -p | cbor2js
     Map(2) {
       1 => -7,
       4 => <Buffer cb e8 13 fb 71 2a 0f ab>
     }

which s exactly what you'd expect. Then the empty unprotected header {} is also fine.

The main payload:
     echo a401624245041a60b9ff14061a60927214390103a101a4617681aa626369782432326437356138322d623364632d343330332d626131382d38653537383963613736313562636f62424562646e016264746a323032312d30342d30326269736f654865616c74682042656c6769756d626d616d4f52472d313030303031363939626d706643566e436f5662736402627467693834303533393030366276706a3131313933343930303763646f626a313938342d31322d3133636e616da462666e664f727477696e62676e674a6f6e6961757863666e74664f525457494e63676e74674a4f4e494155586376657265312e302e30 | xxd -r -p | cbor2js 

     Map(4) {
       -260 => Map(1) {
         1 => {
           dob: '1984-12-13',
           nam: {
             fn: 'Ortwin',
             fnt: 'ORTWIN',
             gn: 'Joniaux',
             gnt: 'JONIAUX'
           },
           v: [
             {
               ci: '22d75a82-b3dc-4303-ba18-8e5789ca7615',
               co: 'BE',
               dn: 1,
               dt: '2021-04-02',
               is: 'eHealth Belgium',
               ma: 'ORG-100001699',
               mp: 'CVnCoV',
               sd: 2,
               tg: '840539006',
               vp: '1119349007'
             }
           ],
           ver: '1.0.0'
         }
       },
       1 => 'BE',
       4 => 1622802196,
       6 => 1620210196
     }

Looks fine. As do the 64 raw bytes of the signature:

      echo 04160c04574da4fcf0dac56a4839e6b95cc57d99a82d8d5bf83e370885a8adfd3b43ed9242d9015756a45a5b51e52f7d5a3f0ab05e4bd4db8a7379f537aa3ce5 | xxd -r -p | wc -c
      64

If we take the certificate and extract the public keys from it

    RAW=$(echo `pbpaste | openssl x509  -noout -pubkey | openssl pkey  -pubin -text | grep '^ '` | sed -e 's/[: ]*//g'
    RAW=$(echo $RAW | sed -e 's/^04//')
    X=$(echo $RAW | cut -c 1-64)
    Y=$(echo $RAW | cut -c 65-128)

we get

	RAW=04de3990ef7b140440e990a2131e042932ac8c3bc3d075e937171517c03a69a68369efc640a10d01e59306861bc361164794113dec01287254cd5dba7cbed7acae
	X=de3990ef7b140440e990a2131e042932ac8c3bc3d075e937171517c03a69a683 
	Y=69efc640a10d01e59306861bc361164794113dec01287254cd5dba7cbed7acae

With X and Y the public keys that should match the signature of above. I've not tried that (https://github.com/ehn-digital-green-development/ehn-sign-verify-python-trivial does not support untagged signatures).

**Comment by asitdm** [comment]
Hi,

thanks to your example, I was able to fix the support for untagged COSE structures. 

Unfortunately the included trustlist service is tailored to the structure provided by https://dgc.a-sit.at/ehn/ and instantiates the public key directly from an PKCS#1/X9.63 structure. For this reason, it is not able to parse certificates. 

I turned the TrustlistService into a protocol and renamed our implementation to DefaultTrustlistService. You should be able to fix this by writing your own trustlist service, which parses your certificate and create a SecKey from it, and provide it as argument in the constructor of the ValidationCore struct.

**Comment by HannesVDB** [comment]
@asitdm awesome!

I will start with a custom TrustlistService and create a PR!
Thanks for your help!

**Comment by vanlooverenkoen** [comment]
For kotlin I found that the trustlist provided by https://dgc.a-sit.at/ehn/ is only implmented in the sample app. not in the hcert library itself. So maybe this should be moved out of this repository and into the sample app. That would make more sense I think.

**Comment by asitdm** [comment]
@HannesVDB Glad to help :)

The proposal sounds interesting, we will discuss that internally!
