### ISSUE TITLE
Handle both tagged AND untagged Cose_Sign1 objects

### ISSUE THREAD

**Issue by martin-lindstrom** [ehn-digital-green-development/ValidationCore#5]
I received some comments from developers that had been looking at your solution that you can't handle when the Cose_Sign1 isn't tagged. See my issue https://github.com/ehn-digital-green-development/hcert-spec/issues/69.

**Comment by asitdm** [comment]
Duplicate of [https://github.com/ehn-digital-green-development/ValidationCore/issues/4](https://github.com/ehn-digital-green-development/ValidationCore/issues/4), see there.
