### ISSUE TITLE
SecKey validation

### ISSUE THREAD

**Issue by HannesVDB** [ehn-digital-green-development/ValidationCore#6]
Following issue #3 I updated my code and implemented my own trustlist service.. 
Which always returns the same certificate for now.

```
class CusomTrustlistService: TrustlistService {
    
    func key(for keyId: Data, keyType: CertType, completionHandler: @escaping (Result<SecKey, ValidationError>) -> ()) {
        let pem = """
MIICLTCCAZYCAQEwDQYJKoZIhvcNAQELBQAwfTELMAkGA1UEBhMCQkUxEzARBgNV
BAgMClNvbWUtU3RhdGUxCzAJBgNVBAoMAlZPMQ4wDAYDVQQLDAVNQUdEQTEPMA0G
A1UEAwwGQ0EtREVWMSswKQYJKoZIhvcNAQkBFhxvcnR3aW4uam9uaWF1eEB2bGFh
bmRlcmVuLmJlMB4XDTIxMDUwNTEwMjEzOVoXDTIyMDUwNTEwMjEzOVowgYcxCzAJ
BgNVBAYTAkJFMRMwEQYDVQQIDApTb21lLVN0YXRlMQswCQYDVQQKDAJWTzEOMAwG
A1UECwwFTUFHREExGTAXBgNVBAMMEERFVi1BdHRlc3RhdGlvbnMxKzApBgkqhkiG
9w0BCQEWHG9ydHdpbi5qb25pYXV4QHZsYWFuZGVyZW4uYmUwWTATBgcqhkjOPQIB
BggqhkjOPQMBBwNCAATeOZDvexQEQOmQohMeBCkyrIw7w9B16TcXFRfAOmmmg2nv
xkChDQHlkwaGG8NhFkeUET3sAShyVM1duny+16yuMA0GCSqGSIb3DQEBCwUAA4GB
AKue+KOyCv4/GAF28PC5ZWL9n9nt86x4LoftWji76uTTC+1QVWLhyFhfvXMfhArn
u9OY/Te1jIyxWROuJv5QVa8h5BMpvV2DdFd7YmpoRN+UuAs6Dd+ve+m82up0Yww/
r4cnUsPorHGNPbBILJOXxhxi9mu1Jrd4pgWr+oXTipft
""".replacingOccurrences(of: "\n", with: "")
        
        guard let data = Data(base64Encoded: pem) else {
            completionHandler(.failure(.KEYSTORE_ERROR(cause: "Invalid PEM")))
            return
        }

        guard let certificate = SecCertificateCreateWithData(nil, data as CFData) else {
            completionHandler(.failure(.KEYSTORE_ERROR(cause: "Unable to create certificate")))
            return
        }

        print("Created certificate: \(certificate)")
        
        guard let publicKey = SecCertificateCopyKey(certificate) else {
            completionHandler(.failure(.KEYSTORE_ERROR(cause: "Unable to create public key")))
            return
        }
        
        print("Used public key: \(publicKey)")
        completionHandler(.success(publicKey))
    }
    
    func updateTrustlist(completionHandler: @escaping (ValidationError?) -> ()) {
        print("Skip updating trustlist")
    }
}
```

From within the public key I should be able to validate the signature.

What I noticed in the code is that the signature to validate is mapped to a new struct of data which is CBOR signed..
**Why is this extra business logica applied?**

For our certificate / data this flow won't work.. 

I tried to simply the validation of the signature by:

```
private func hasCoseSign1ValidSignature(for key: SecKey) -> Bool {
        guard let signedData = signatureStruct else {
            print("Cannot create Sign1 structure.")
            return false
        }
        
        let alg: SecKeyAlgorithm = .ecdsaSignatureMessageX962SHA256
        
        var error: Unmanaged<CFError>?
        guard SecKeyVerifySignature(key, alg, signedData as CFData, signature as CFData, &error) else {
            print("Can't verify signature \(error)")
            return false
        }
        return true
    }
```

But it seems I can't very the signature.
I think it's related to the `signatureStruct`

**Is it possible to explain why the signatureStruct is created?**

**Comment by dirkx** [comment]
But if this is what the verifier fetches - why not limit it to just the KID and a X and Y public key tuple ?

**Comment by dirkx** [comment]
@Hannes - If you want a more realistic test cert - look at https://github.com/ehn-digital-green-development/masterlist-cert-generator and/or copy the NL example.

**Comment by HannesVDB** [comment]
Maybe it's due to my little knowledge of certificates in iOS but I don't fully understand how I can verify the kid or the X-Y tuple..

**Comment by asitdm** [comment]
The signature struct is the representation of COSE according to [RFC8152](https://datatracker.ietf.org/doc/html/rfc8152#section-4.4), of which the signature is created. The SecKey creation should not have an influence on the verification process, as long as it is the correct public key type. Your trustlist-code looks fine to me.

A common problem for EC signature verification on iOS is to provide the signature in SecKeyVerifySignature as raw signature, instead of the required ASN1 structure.

I just published our feature/compatibility_tests branch, which contains the TestTrustlistService class. This class creates public keys from Base64 encoded certificates, used in the COSE signature verification process. Maybe you can use some of the code? But please keep in mind, that this branch is still work in progress. The trustlist service is subject to change as well (but should be able to parse certificates after the rework ;-) ).

**Comment by DKvarn** [comment]
@HannesVDB I have also started to make my own TrustListService with the same certificate flow as you have, I got it to work with the current Cose.verifySignature function so I don't think you need your own hasCoseSign1ValidSignature function. 

I haven't tested it but one important thing you can find in Cose.verifySignature is `Asn1Encoder().convertRawSignatureIntoAsn1(rawSignature)` and @asitdm mention the ASN1 structure in the comment above so I think you need that in your own validation function.

**Comment by asitdm** [comment]
@HannesVDB  The trustlist was refactored and does support Base64 encoded certificates now. You could try to create a key using an TrustEntry directly. Or did you already succeed to verify signatures?

**Comment by asitdm** [comment]
Assuming it is working now, please reopen if this is not the case.
